apiVersion: v1
kind: Namespace
metadata:
  name: reboot-manager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reboot-manager
  namespace: reboot-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reboot-manager
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - post
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reboot-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reboot-manager
subjects:
- kind: ServiceAccount
  name: reboot-manager
  namespace: reboot-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reboot-manager
  namespace: reboot-manager
spec:
  selector:
    matchLabels:
      app: reboot-manager
  replicas: 2
  template:
    metadata:
      labels:
        app: reboot-manager
    spec:
      serviceAccountName: reboot-manager
      containers:
      - name: reboot-manager
        image: jasonn3/kubernetes_reboot_manager:latest
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reboot-manager
  namespace: reboot-manager
spec:
  selector:
    app: reboot-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: ClusterIP
