apiVersion: v1
kind: Namespace
metadata:
  name: reboot-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reboot-manager
  namespace: reboot-manager
spec:
  selector:
    matchLabels:
      app: reboot-manager
  replicas: 2
  template:
    metadata:
      labels:
        app: reboot-manager
    spec:
      containers:
      - name: reboot-manager
        image: jasonn3/kubernetes-reboot-manager:latest
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reboot-manager
  namespace: reboot-manager
spec:
  selector:
    app: reboot-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: ClusterIP
